exports.frases = [
  "Você não precisa ver a escada inteira, apenas dê o primeiro passo.",
  "A disciplina é a ponte entre metas e conquistas.",
  "Não espere por oportunidades. Crie-as.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Você é mais forte do que pensa e está mais perto do que imagina.",
  "Grandes realizações começam com pequenos passos.",
  "Acredite em você mesmo e tudo será possível.",
  "Mesmo que ninguém acredite em você, continue.",
  "Cada dia é uma nova chance para recomeçar.",
  "Coragem não é a ausência do medo, mas a decisão de que algo é mais importante que ele.",
  "Não desista até se orgulhar.",
  "Desafios são o que tornam a vida interessante.",
  "Seja a mudança que você quer ver no mundo.",
  "A persistência realiza o impossível.",
  "Tudo o que você precisa para vencer já está dentro de você.",
  "Se não puder voar, corra. Se não puder correr, ande. Mas continue em frente.",
  "O fracasso é apenas a oportunidade de recomeçar com mais inteligência.",
  "Não importa o quão devagar você vá, desde que não pare.",
  "Levanta, sacode a poeira e dá a volta por cima.",
  "Ninguém é como você, e esse é o seu poder.",
  "Acredite: você consegue.",
  "A jornada de mil milhas começa com um passo.",
  "Você é capaz de coisas incríveis.",
  "Nunca subestime o poder de um novo começo.",
  "Você não veio até aqui para desistir agora.",
  "Foque no progresso, não na perfeição.",
  "A única maneira de chegar ao topo é começar de onde você está.",
  "Grandes sonhos exigem coragem.",
  "Confie no processo.",
  "Nada é tão nosso quanto os nossos sonhos.",
  "Dias difíceis constroem pessoas fortes.",
  "Seja mais forte que sua melhor desculpa.",
  "A ação é a chave fundamental para todo sucesso.",
  "Você nunca sabe o quão forte é até que ser forte seja sua única escolha.",
  "Acredite no que você está fazendo.",
  "Seja luz na vida de alguém — inclusive na sua.",
  "Transforme obstáculos em degraus.",
  "Sua história ainda está sendo escrita.",
  "Toda conquista começa com a decisão de tentar.",
  "O seu melhor ainda está por vir.",
  "Paciência, foco e consistência vencem no final.",
  "Tudo tem o tempo certo para acontecer.",
  "Você pode mais do que imagina.",
  "O mundo precisa do que só você pode oferecer.",
  "Insista, persista, nunca desista.",
  "Quem acredita, realiza.",
  "Vá no seu tempo, mas vá.",
  "A motivação te inicia, o hábito te mantém.",
  "Comece onde você está, use o que você tem, faça o que puder.",
  "Não é sobre ser o melhor, é sobre ser melhor do que ontem."
];
